#!/usr/bin/env bash
# Emits the "Verified baselines" block for plans/handoff.md — generated evidence, never
# hand-transcribed. Single-repo template: copy to scripts/handoff-baselines.sh alongside
# gate.sh. For a multi-repo workspace, loop over the repos (see ibkr-bot's version).
set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"

echo "## Verified baselines ($(date +%F) — generated by scripts/handoff-baselines.sh; re-verify in step 0)"
echo "- HEAD: \`$(git -C "$REPO" log -1 --format='%h %s')\`"
status=$(git -C "$REPO" status --porcelain)
if [ -z "$status" ]; then
  echo "- tree: clean"
else
  echo "- tree NOT clean (staged/modified):"
  echo "$status" | sed 's/^/      /'
fi
out=$("$REPO/scripts/gate.sh" 2>&1); rc=$?
echo "- gate (exit $rc):"
echo "$out" | grep -E "^== |passed|shasum|sweep-verify|no-exec-deps" | sed 's/^/      /'
